name: Convert PowerPoint to PDF

on:
  push:
    paths:
      - 'slides/*.ppt'
      - 'slides/*.pptx'
  workflow_dispatch:

permissions:
  contents: write  # PDFファイルのリポジトリへのpush権限
  pages: write    # GitHub Pagesへのデプロイ権限
  id-token: write # GitHub Pagesのデプロイに必要な認証

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up LibreOffice and Japanese fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y libreoffice fonts-ipafont fonts-ipaexfont

    - name: Create output directory
      run: mkdir -p pdfs

    - name: Convert PPT to PDF
      run: |
        for file in slides/*.ppt*; do
          if [ -f "$file" ]; then
            filename=$(basename -- "$file")
            name="${filename%.*}"
            echo "Converting $filename to PDF..."
            # フォント埋め込みオプションを追加してPDF変換
            libreoffice --headless --convert-to "pdf:writer_pdf_Export:EmbedFonts=1" --outdir pdfs "$file"
            if [ $? -eq 0 ]; then
              echo "Successfully converted $filename"
            else
              echo "Error converting $filename"
              exit 1
            fi
          fi
        done

    - name: Commit PDF files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pdfs/*.pdf
        git commit -m "Convert PowerPoint to PDF" || echo "No changes to commit"
        git push